DROP TABLE AVIARY;
DROP TABLE ANIMAL;
DROP TABLE EMPLOYEE;

CREATE TABLE AVIARY (
    VOLUME            	INTEGER NOT NULL,
    NO_            	INTEGER NOT NULL,
    IS_BUSY       	BOOLEAN NOT NULL
);

ALTER TABLE AVIARY ADD CONSTRAINT AVIARY_pk PRIMARY KEY (NO_);


CREATE TABLE ANIMAL (
    ID               	INTEGER NOT NULL,
    AGE          	INTEGER NOT NULL,
    NAME              	VARCHAR(100) NOT NULL,
    AVIARY_id        	INTEGER
);

ALTER TABLE ANIMAL ADD SPICHES_NAME VARCHAR(100);
ALTER TABLE ANIMAL ADD CONSTRAINT AGE_MORE_THEN_ZERO CHECK (AGE > 0);
ALTER TABLE ANIMAL ADD CONSTRAINT ANIMAL_pk PRIMARY KEY (id);
ALTER TABLE ANIMAL ADD CONSTRAINT ANIMAL_AVIARY_fk FOREIGN KEY (AVIARY_id) 
    REFERENCES AVIARY (NO_) ON DELETE SET NULL;


CREATE TABLE EMPLOYEE (
    ID             	INTEGER NOT NULL,
    LASTNAME            VARCHAR(100) NOT NULL,
    FIRSTNAME  		VARCHAR(100) NOT NULL,
    SALARY              INTEGER NOT NULL,
    ANIMAL_id        	INTEGER
    
);

ALTER TABLE EMPLOYEE 
    ADD CONSTRAINT EMPLOYEE_pk PRIMARY KEY (id);
    
ALTER TABLE EMPLOYEE 
    ADD CONSTRAINT EMPLOYEE_ANIMAL_fk FOREIGN KEY (ANIMAL_id)
        REFERENCES ANIMAL (id) ON DELETE SET NULL;