-- task1
SELECT LASTNAME, SALARY, BONUS 
FROM EMPLOYEE 
WHERE SEX = 'F';

-- task2
SELECT LASTNAME, SALARY, COMM 
FROM EMPLOYEE 
WHERE SALARY > 20000 AND HIREDATE > '1979-12-31';

-- task3
SELECT LASTNAME, SALARY, BONUS, COMM 
FROM EMPLOYEE 
WHERE SALARY > 22000 AND (BONUS = 400 OR BONUS = 500) AND COMM < 1900 
ORDER BY LASTNAME;

-- task4
SELECT PROJNO, ACTNO, EMSTDATE, EMENDATE 
FROM EMP_ACT 
WHERE PROJNO LIKE 'AD%' AND (ACTNO = 10 OR ACTNO = 80 OR ACTNO = 180) 
ORDER BY PROJNO, ACTNO;

-- task5
SELECT E.LASTNAME, E.FIRSTNME, D.DEPTNAME 
FROM EMPLOYEE AS E
JOIN DEPT AS D ON E.WORKDEPT = D.DEPTNO 
ORDER BY D.DEPTNAME, E.LASTNAME, E.FIRSTNME;

-- task6
SELECT E.LASTNAME, E.FIRSTNME, D.DEPTNAME, E.JOB 
FROM EMPLOYEE AS E
INNER JOIN DEPT AS D ON E.WORKDEPT = D.DEPTNO 
WHERE E.WORKDEPT BETWEEN 'A02' AND 'D22' AND E.JOB  <> 'MANAGER'
ORDER BY D.DEPTNAME, E.JOB, E.LASTNAME, E.FIRSTNME;

-- task7
SELECT DISTINCT E.PROJNO, P.PROJNAME, E.ACTNO 
FROM EMP_ACT AS E   
INNER JOIN PROJ AS P ON E.PROJNO = P.PROJNO 
WHERE E.PROJNO LIKE 'AD%'
ORDER BY E.PROJNO, E.ACTNO;

-- task8
SELECT E.WORKDEPT, M.LASTNAME, E.LASTNAME, M.HIREDATE, E.HIREDATE
FROM EMPLOYEE AS E 
JOIN EMPLOYEE AS M ON E.WORKDEPT = M.WORKDEPT
JOIN DEPT AS D ON D.MGRNO = M.EMPNO
WHERE E.WORKDEPT = 'A00' AND E.HIREDATE < M.HIREDATE;